newspaperlist:

  newspaper_1:
    name: "El-Espectador"
    website: 'https://www.elespectador.com'
    XPATH_links: '//div[@class="GlobalContainer"]//div[@class="Card-title card-title h5"]//a[@class ="card-link"]/@href'
    XPATH_news_details:
      Title: '//h1[@class="Article-Title"]/text()'
      Body: '//div[@class="Article-Content"]//p[@class="font--secondary"]//text()'
      #ImgUrl: '//figure[@class="Article-Image"]/img/@src'

  newspaper_2:
    name: "El-Tiempo"
    website: 'https://www.eltiempo.com'
    XPATH_links: '//h3[@class="title-container"]/a/@href'
    XPATH_news_details:
      Title: '//div[@class="titulo-principal-bk"]/h1//text()'
      Date: '//span[@class="fecha"]/text()'
      Summary: '//div[@class="lead"]/p//text()'
      Body: '//div[@class="articulo-contenido"]//p[@class="contenido"]/text()'
      #ImgUrl: '//div[@class="recurso_apertura"]//@src'
  
